crictl pull ccr.ccs.tencentyun.com/cube-studio/redis:7.4 &&
crictl pull prom/prometheus:v2.27.1 &&
crictl pull docker.io/library/busybox:1.36.0 &&
crictl pull mpioperator/kubectl-delivery:latest &&
crictl pull projecthami/hami:v2.3.13 &&
crictl pull nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 &&
crictl pull prom/node-exporter:v1.5.0 &&
crictl pull kubeflow/training-operator:v1-8a066f9 &&
crictl pull nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 &&
crictl pull ubuntu:20.04 &&
crictl pull volcanosh/vc-scheduler:v1.7.0 &&
crictl pull kubernetesui/metrics-scraper:v1.0.8 &&
crictl pull istio/pilot:1.15.0 &&
crictl pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.25.16 &&
crictl pull alpine:3.10 &&
crictl pull quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 &&
crictl pull carlosedp/addon-resizer:v1.8.4 &&
crictl pull ccr.ccs.tencentyun.com/cube-argoproj/argoexec:v3.4.3 &&
crictl pull mysql:8.0.32 &&
crictl pull grafana/grafana:9.5.20 &&
crictl pull ccr.ccs.tencentyun.com/cube-argoproj/argocli:v3.4.3 &&
crictl pull postgres:11.5 &&
crictl pull volcanosh/vc-webhook-manager:v1.7.0 &&
crictl pull quay.io/prometheus-operator/prometheus-operator:v0.46.0 &&
crictl pull liangjw/kube-webhook-certgen:v1.1.1 &&
crictl pull ccr.ccs.tencentyun.com/cube-studio/kube-rbac-proxy:0.14.1 &&
crictl pull kubernetesui/dashboard:v2.6.1 &&
crictl pull python:3.9 &&
crictl pull istio/proxyv2:1.15.0 &&
crictl pull minio/minio:RELEASE.2023-04-20T17-56-55Z &&
crictl pull ccr.ccs.tencentyun.com/cube-argoproj/workflow-controller:v3.4.3 &&
crictl pull volcanosh/vc-controller-manager:v1.7.0 &&
wait
