apiVersion: v1
kind: Config
clusters:
- name: "cube-k8s"
  cluster:
    server: "https://192.168.1.170/k8s/clusters/c-86snm"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMzT1RReApPVFEyTlRBZUZ3MHlOakExTWpJd016RXhNRFZhRncwek5qQTFNVGt3TXpFeE1EVmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56YzVOREU1TkRZMU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXE1RnZKZWJrVlk0SQphSDZhallEZVgyTFh5YlY0RnlSVFgzNkV3b\
      m9HVVNUQk9PNmdJeW00WlJjVWZERlBoYUZva3ZCNXFGeU1XQkV2CmNMN2VCMFVwNEtOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      ExqczQxUjl5VzUvU1RzRldNV29FSHhYV3ZlTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEUwpIT\
      HVEeHpVRHErVGpwcVhnTTV3M2dUTHdsRDhuL3RXQmZZdDJuUE9oQndJZ1JuWWhxL1J0empnMWpSZ\
      FQxbGhaCkVFYk5NNlFTN0IvdkY2YkNqd3ZDVlVNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
- name: "cube-k8s-192.168.1.171"
  cluster:
    server: "https://192.168.1.171:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEkyTURVeU5UQTRNRE16TmxvWERUTTJNRFV5TWpBNE1ETXpObG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1VUEFvMk9kVW1HCkVGVktHeE10K25pbzlQWkxaaXRmN1l3enhycGtBaDBqbk52TnR2REZQZ\
      WI3VmRBN2dHT0NTNnB0SUxiaWVGdWgKUndWeVJLdGtJZ0pOZ1VDZHRVT2FTSUVhUjRxdk1aR2hBR\
      Uh6TndLVlc3ZDYwY2xIVFZzSEhpa2V3NTlJZnFNMApOd0tzc1piblUrby9kOHFqaEh0QktDTzRKd\
      XFVV3RaVWp0N1VEOUg5NnFjSzBQWGQwSW42ZWI3bmxCK0RYZ2I2CmZocG1nQlRXenRQUmdzRFVuW\
      VNndG8zMzJWeXdPM2VqMGthTzZZaHlNQlcyQTB0NSttelNIdThDdnNCNUQ2TzMKZDJ6OFAwVWJEe\
      UlVL2xpMHY0OGR5end2K1RGbzJlZERYa0xFajQ3Zk5jWmZ1Z25kbzRDWVByYmpFRWtUYW9QTgplb\
      XNpTmF3ZEV2Y0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTFBnZXdCdVZKM1JQN0VTLzdvd1ZJR2gxNk9mTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQjVFRnpLcXhMaTFqS0Y3dmNaWGdGbTFxdVlFU2dXTmREUm9Ye\
      UxBMmVsWHkzclc5NXpvaGtpWmVsYgpDcCtnNmJEWFhjM2h3LzZORFQ3TWJ0aVVwNWdTZU9CZlVKN\
      XNCWU1FaVd2RHJaR2h5R3VuSGl0VGczanBUNGtpCmtoQ3JQb2Ura3dlczJsVm9xZEd2VzZnSXJIS\
      VVTMm5kM2tRMnhtT0RaVEJ1ZStXSE1NYnZDR3YxV1Vxd2VXc1MKUWdGaXJJbmg3RndTa2V2dnNQO\
      CtOU3VOdkk3b1VFNSs0b2xCaDRWSFl6d0l3Qmlmek9uZjltN1kwWkllZHFFSApsRWFYUDI1SlM1e\
      kQ2M2g3QzlYMVpJR2hqN1JpcGNrTWFNL0xoc3l2WXZYYzNoTURKMDB3ZXNoMG96RzQ1UkpNCmFab\
      E0xSUFIa0JodFBzRXl1WDg3d0Qxa3Z5QngKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
- name: "cube-k8s-192.168.1.172"
  cluster:
    server: "https://192.168.1.172:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEkyTURVeU5UQTRNRE16TmxvWERUTTJNRFV5TWpBNE1ETXpObG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1VUEFvMk9kVW1HCkVGVktHeE10K25pbzlQWkxaaXRmN1l3enhycGtBaDBqbk52TnR2REZQZ\
      WI3VmRBN2dHT0NTNnB0SUxiaWVGdWgKUndWeVJLdGtJZ0pOZ1VDZHRVT2FTSUVhUjRxdk1aR2hBR\
      Uh6TndLVlc3ZDYwY2xIVFZzSEhpa2V3NTlJZnFNMApOd0tzc1piblUrby9kOHFqaEh0QktDTzRKd\
      XFVV3RaVWp0N1VEOUg5NnFjSzBQWGQwSW42ZWI3bmxCK0RYZ2I2CmZocG1nQlRXenRQUmdzRFVuW\
      VNndG8zMzJWeXdPM2VqMGthTzZZaHlNQlcyQTB0NSttelNIdThDdnNCNUQ2TzMKZDJ6OFAwVWJEe\
      UlVL2xpMHY0OGR5end2K1RGbzJlZERYa0xFajQ3Zk5jWmZ1Z25kbzRDWVByYmpFRWtUYW9QTgplb\
      XNpTmF3ZEV2Y0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTFBnZXdCdVZKM1JQN0VTLzdvd1ZJR2gxNk9mTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQjVFRnpLcXhMaTFqS0Y3dmNaWGdGbTFxdVlFU2dXTmREUm9Ye\
      UxBMmVsWHkzclc5NXpvaGtpWmVsYgpDcCtnNmJEWFhjM2h3LzZORFQ3TWJ0aVVwNWdTZU9CZlVKN\
      XNCWU1FaVd2RHJaR2h5R3VuSGl0VGczanBUNGtpCmtoQ3JQb2Ura3dlczJsVm9xZEd2VzZnSXJIS\
      VVTMm5kM2tRMnhtT0RaVEJ1ZStXSE1NYnZDR3YxV1Vxd2VXc1MKUWdGaXJJbmg3RndTa2V2dnNQO\
      CtOU3VOdkk3b1VFNSs0b2xCaDRWSFl6d0l3Qmlmek9uZjltN1kwWkllZHFFSApsRWFYUDI1SlM1e\
      kQ2M2g3QzlYMVpJR2hqN1JpcGNrTWFNL0xoc3l2WXZYYzNoTURKMDB3ZXNoMG96RzQ1UkpNCmFab\
      E0xSUFIa0JodFBzRXl1WDg3d0Qxa3Z5QngKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
- name: "cube-k8s-192.168.1.173"
  cluster:
    server: "https://192.168.1.173:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEkyTURVeU5UQTRNRE16TmxvWERUTTJNRFV5TWpBNE1ETXpObG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1VUEFvMk9kVW1HCkVGVktHeE10K25pbzlQWkxaaXRmN1l3enhycGtBaDBqbk52TnR2REZQZ\
      WI3VmRBN2dHT0NTNnB0SUxiaWVGdWgKUndWeVJLdGtJZ0pOZ1VDZHRVT2FTSUVhUjRxdk1aR2hBR\
      Uh6TndLVlc3ZDYwY2xIVFZzSEhpa2V3NTlJZnFNMApOd0tzc1piblUrby9kOHFqaEh0QktDTzRKd\
      XFVV3RaVWp0N1VEOUg5NnFjSzBQWGQwSW42ZWI3bmxCK0RYZ2I2CmZocG1nQlRXenRQUmdzRFVuW\
      VNndG8zMzJWeXdPM2VqMGthTzZZaHlNQlcyQTB0NSttelNIdThDdnNCNUQ2TzMKZDJ6OFAwVWJEe\
      UlVL2xpMHY0OGR5end2K1RGbzJlZERYa0xFajQ3Zk5jWmZ1Z25kbzRDWVByYmpFRWtUYW9QTgplb\
      XNpTmF3ZEV2Y0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTFBnZXdCdVZKM1JQN0VTLzdvd1ZJR2gxNk9mTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQjVFRnpLcXhMaTFqS0Y3dmNaWGdGbTFxdVlFU2dXTmREUm9Ye\
      UxBMmVsWHkzclc5NXpvaGtpWmVsYgpDcCtnNmJEWFhjM2h3LzZORFQ3TWJ0aVVwNWdTZU9CZlVKN\
      XNCWU1FaVd2RHJaR2h5R3VuSGl0VGczanBUNGtpCmtoQ3JQb2Ura3dlczJsVm9xZEd2VzZnSXJIS\
      VVTMm5kM2tRMnhtT0RaVEJ1ZStXSE1NYnZDR3YxV1Vxd2VXc1MKUWdGaXJJbmg3RndTa2V2dnNQO\
      CtOU3VOdkk3b1VFNSs0b2xCaDRWSFl6d0l3Qmlmek9uZjltN1kwWkllZHFFSApsRWFYUDI1SlM1e\
      kQ2M2g3QzlYMVpJR2hqN1JpcGNrTWFNL0xoc3l2WXZYYzNoTURKMDB3ZXNoMG96RzQ1UkpNCmFab\
      E0xSUFIa0JodFBzRXl1WDg3d0Qxa3Z5QngKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "cube-k8s"
  user:
    token: "kubeconfig-user-kvxp9prt4p:j2cpdd9shd5zxb75mtd8j4rjwlw5nk8srktwlfs4v56n8vvpcqz9cp"


contexts:
- name: "cube-k8s"
  context:
    user: "cube-k8s"
    cluster: "cube-k8s"
- name: "cube-k8s-192.168.1.171"
  context:
    user: "cube-k8s"
    cluster: "cube-k8s-192.168.1.171"
- name: "cube-k8s-192.168.1.172"
  context:
    user: "cube-k8s"
    cluster: "cube-k8s-192.168.1.172"
- name: "cube-k8s-192.168.1.173"
  context:
    user: "cube-k8s"
    cluster: "cube-k8s-192.168.1.173"

current-context: "cube-k8s"

